# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3249d64a1ed06ce42f15e28febdad33cca193ea9670d199f50bd3efa5afd6fd0919c03785d289d2ac654a396085a956a5b50a7f7509e29b969c66a8fc92d2c85

test:
  secret_key_base: 6e375bcec192c58231a015f83bb2462db9f12295f41728175e583895ccbf4ee2b2a6f245fa60abc3a9b2af2ddeeda9d7ba7f9dfcb74213d310ef2ae1eb2accf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 95c800e43841d68f713bf3704247d0a3bc14e3598b08d371d4197547e04b951d4d8656ca850f7731eb80db2365e9f9495dd9249e0b30adba47c1fcb35468281b
